#!/usr/bin/env python3
"""peer-sends-recent — regenerate sartor/memory/peer-sends/RECENT.md from JSONL log.

Reads the last N peer-send records across all monthly JSONL files and emits a
human-readable rollup. Designed to be called from the morning-briefing
scheduled task and/or by hand.

Usage:
    python peer-sends-recent.py [--n 20]
"""
from __future__ import annotations

import argparse
import datetime
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
PEER_SENDS_DIR = REPO_ROOT / "sartor" / "memory" / "peer-sends"


def load_recent(n: int) -> list[dict]:
    if not PEER_SENDS_DIR.exists():
        return []
    files = sorted(PEER_SENDS_DIR.glob("*.jsonl"), reverse=True)
    records: list[dict] = []
    for f in files:
        with f.open("r", encoding="utf-8") as fh:
            for line in fh:
                line = line.strip()
                if not line:
                    continue
                try:
                    records.append(json.loads(line))
                except json.JSONDecodeError:
                    continue
        if len(records) >= n * 2:
            break
    records.sort(key=lambda r: r.get("ts", ""), reverse=True)
    return records[:n]


def count_recent_24h(records: list[dict]) -> int:
    cutoff = (datetime.datetime.now(datetime.timezone.utc) - datetime.timedelta(hours=24)).isoformat()
    return sum(1 for r in records if r.get("ts", "") >= cutoff)


def render(records: list[dict]) -> str:
    last_24h = count_recent_24h(records)
    now = datetime.datetime.now(datetime.timezone.utc).isoformat(timespec="seconds")

    lines = [
        "---",
        "type: meta",
        f"generated: {now}",
        "tags: [domain/infrastructure, meta/audit, project/peer-comms-uplift]",
        "---",
        "",
        "# Recent peer-sends",
        "",
        f"Auto-regenerated by `scripts/peer-sends-recent.py`. Last 24h: **{last_24h} sends**.",
        "",
        "| When (UTC) | Peer | Path | Slug | Chars | Ack | Flags | Status |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for r in records:
        ts = r.get("ts", "")[:16].replace("T", " ")
        peer = r.get("peer", "?")
        path = r.get("path", "?")
        slug = r.get("slug", "?")
        chars = r.get("char_count", 0)
        ack = "✓" if r.get("ack_seen") else "—"
        flags = ", ".join(r.get("judgment_flags", [])) or ""
        status = r.get("status", "?")
        # Heavy path links to the inbox file via commit SHA prefix in the slug column
        if path == "heavy" and r.get("commit_sha"):
            sha = r["commit_sha"][:8]
            slug_cell = f"{slug} ({sha})"
        else:
            slug_cell = slug
        lines.append(f"| {ts} | {peer} | {path} | {slug_cell} | {chars} | {ack} | {flags} | {status} |")

    if not records:
        lines.append("| _no sends recorded yet_ | | | | | | | |")

    lines += [
        "",
        "## How to read this",
        "",
        "- **path** = `light` (direct tmux send) or `heavy` (inbox file + git commit + push)",
        "- **slug** for heavy sends shows the first 8 chars of the commit SHA in parens — find the directive at `sartor/memory/inbox/{peer}/{ts}-{slug}.md`",
        "- **ack** = ✓ when capture-pane after 4s showed a processing indicator (Cogitating/Forming/tool call); — when no indicator visible (peer may still be working, but the send isn't confirmed)",
        "- **flags** = §7 content-judgment hits (pricing change / money / medical / kid PII patterns); the script does NOT block on flags, peer can decline",
        "",
        "Full per-send detail is in `sartor/memory/peer-sends/{YYYY-MM}.jsonl`.",
    ]
    return "\n".join(lines) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--n", type=int, default=20, help="number of recent sends to show (default 20)")
    args = ap.parse_args()

    records = load_recent(args.n)
    PEER_SENDS_DIR.mkdir(parents=True, exist_ok=True)
    out = PEER_SENDS_DIR / "RECENT.md"
    out.write_text(render(records), encoding="utf-8")
    print(f"wrote {out} ({len(records)} records, {count_recent_24h(records)} in last 24h)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
